### ISSUE TITLE
syncing notebooks and data have different purposes, needs

### ISSUE THREAD

**Issue by deszoeke** [jtomfarrar/submersible_humidity_sensor#2]
### Git won't sync data.
I found that git wouldn't sync even modestly-sized data (RBR thermistor .log) files; and these furthermore prevented pushing of any changes to this repo.

Most of the directories in `./data` were empty so I deleted them for now.

`./data/raw/` had useless stubs of data. I just re-added an (almost) empty folder, but with `./data/.gitignore` to the repository.

Users needs to keep the data needed by the notebook their local tree of `./data/`. _Do not track these files with git._

#### Need to refactor directories into /data/ and /code/.
The practice of syncing code with git, and data by some other way suggests storing data and code in separate places, at least once code is ready to push to the main branch.

### We want to share Jupyter notebooks with git, but this isn't smooth either.
Notebooks are full of hidden state and have arbitrary changes in metadata. Standard git doesn't diff them easily.

Tools like `nbdime` and `Jupytext` exist for improved notebook experience.

**Comment by jtomfarrar** [comment]
HI Simon-- thanks for this.  I think I agree with all that you say here...  If we move to *.jl notebooks, I think that is a bit smoother for git syncing.  I don't have much experience with this, but it seems like a major advantage of Julia notebooks.

**Comment by deszoeke** [comment]
> move to *.jl notebooks

Julia source (not in a notebook) is in `.jl` files. I am using an IJulia kernel to compile and interpret the julia code in my `.ipynb` notebook. Of course, I can just paste all the julia cells into a non-notebook .jl source file. That's just what [Jupytext](https://jupytext.readthedocs.io/en/latest/install.html) does with some automation.

Whereas [nbdime](https://nbdime.readthedocs.io/en/latest/) allows git to reason with the notebook itself.

It looks like Jupytext can be enabled with the command palette within JupyterLab.

**Comment by deszoeke** [comment]
I got jupytext to work, and Git is tracking the **percent script summarizing the notebook**. The percent script separates cells with 
```julia
# %%
```
lines. AFACT, it the percent script records the code sent to the kernel, not necessarily what's saved in the notebook.

The **data** will be stored in the `/data` directory but untracked by `.gitignore`.

Seeing the opened issues suitably worked-around, I'm going to close this.
